# Generated by Django 6.1.1 on 2026-09-28 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('patients_imported', models.PositiveIntegerField(default=0)),
                ('observations_imported', models.PositiveIntegerField(default=0)),
                ('failures', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(max_length=64, unique=True)),
                ('given_name', models.CharField(blank=True, max_length=255)),
                ('family_name', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=16)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['family_name', 'given_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('code_system', models.CharField(blank=True, max_length=255)),
                ('display', models.CharField(blank=True, max_length=255)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_unit', models.CharField(blank=True, max_length=64)),
                ('value_text', models.CharField(blank=True, max_length=255)),
                ('components', models.JSONField(blank=True, default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='clinical.patient')),
            ],
            options={
                'ordering': ['-effective_at', 'id'],
            },
        ),
    ]
