# Generated by Django 6.1.1 on 2026-09-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['patient', '-effective_at'], name='clinical_ob_patient_50a3f3_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['family_name', 'given_name'], name='clinical_pa_family__524d56_idx'),
        ),
    ]
