# Generated by Django 6.1.1 on 2026-09-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='checkpoint',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
